import = ["~/.config/alacritty/gruber.toml"]

[scrolling]
history = 10000

[font]
#normal = { family = "Agave", style = "Regular" }
#normal = { family = "Monoid", style = "Regular" }
#normal = { family = "Meslo LG S", style = "Regular" }
#normal = { family = "Jetbrains Mono", style = "Regular" }
#normal = { family = "Tweak Mono", style = "Regular" }
normal = { family = "Iosevka548", style = "Regular" }

#bold = { style = "Regular" }

size = 19
offset = { y = -5 }

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
opacity = 1
dynamic_title = true

[window.padding]
x = 15
y = 15


[shell]
program = "nvim"
args = ["+terminal", "zsh"]
